<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\Build\Grand.Common.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\Business\Grand.Business.Core\Grand.Business.Core.csproj" />
    <ProjectReference Include="..\..\Core\Grand.Infrastructure\Grand.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Grand.Cms.Client.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
